# Name of the action:
  name: Build and deploy

  on:
    push:
      branches: [ "master" ]
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Build
          uses: actions/setup-node@v4
        - run: npm ci
        - run: npm run build

        - name: Deploy
          uses: JamesIves/actions-gh-pages@v4
          with:
            folder: _site
